spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.110:3306/sell?characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null #当对象中返回的是null时，不会吸纳事出来
  redis:
    host: 192.168.0.110
    port: 6379
    password:
server:
  context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: /Users/kokioyao/Documents/log/sell/boring.log
#  level: info
#  path: /Users/kokioyao/Documents/log/sell

wechat:
  mp-app-secret: cb906aef1e8e0387b7ac1fae8800f86b
  mp-app-id: wx9fcaa5a519b13b2b
  templateId:
    orderStatus: PuDjsu0paBBdrHKaaamaxx8tPW8EK04kLTQnjqgYJmY

projectUrl:
  sell: http://footman77.natapp1.cc

logging:
  level:
    cn.footman.sell.dataobject.mapper: trace


mybatis:
  config-location: classpath:SqlMapConfig.xml
  mapper-locations: classpath:mapper/*.xml
